services:
- type: web
  name: jen-api
  runtime: python
  repo: https://github.com/govtechmy/myds-gen
  branch: main
  plan: free
  envVars:
  - key: langchain_pk
    sync: false
  - key: langchain_sk
    sync: false
  - key: LANGSMITH_API_KEY
    sync: false
  - key: LANGSMITH_TRACING
    sync: false
  - key: GEMINI_API_KEY
    sync: false
  - key: PORT
    sync: false
  region: singapore
  buildCommand: pip install .
  startCommand: uvicorn src.api:app --host 0.0.0.0 --port $PORT
version: "1"
